name = "authworker"
main = "src/index.ts"
compatibility_date = "2026-02-12"
compatibility_flags = ["nodejs_compat"]

# D1 binding (we create DB next)
[[d1_databases]]
binding = "exquisitebnb_cms"
database_name = "exquisitebnb_cms"
database_id = "9fde6a2e-9f52-4c43-adcc-9db712a4876f"
migrations_dir = "migrations"

[vars]
CORS_ORIGIN = "*"

[env.production]
name = "authworker"

[[env.production.d1_databases]]
binding = "exquisitebnb_cms"
database_name = "exquisitebnb_cms"
database_id = "9fde6a2e-9f52-4c43-adcc-9db712a4876f"
migrations_dir = "migrations"